Parameters:
  EnvironmentName:
        Description: An environment name that will be added to resource names
        Type: String

Resources:
  WebServerSecGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow http to our host and ssh from local only
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebAppLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt-get -y update
            sudo apt-get -y install git
            sudo apt-get -y install docker.io
            sudo usermod -aG docker ubuntu
            docker pull yaraselim1994/cloud-devops-capstone
            docker run -d -p 80:80 yaraselim1994/cloud-devops-capstone
        ImageId: ami-003634241a8fcdec0
        SecurityGroups:
        - Ref: WebServerSecGroup
        InstanceType: t2.micro
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '10'
  WebAppGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB-NETS"
        LaunchConfigurationName:
          Ref: WebAppLaunchConfig
        MinSize: '1'
        MaxSize: '2'
        TargetGroupARNs:
        - Fn::ImportValue: !Sub "${EnvironmentName}-WebAppTargetGroup"