apiVersion: v1
kind: Service
metadata:
  name: uc-capstone
spec:
  type: LoadBalancer
  selector:
    app: uc-capstone
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc-capstone-deploy
spec:
  selector:
    matchLabels:
      app: uc-capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: uc-capstone
    spec:
      containers:
      - name: uc-capstone-pod
        image: yaraselim1994/cloud-devops-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
