apiVersion: v1
kind: Service
metadata:
  name: Cloud-DevOps-Capstone
spec:
  type: LoadBalancer
  selector:
    app: Cloud-DevOps-Capstone
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cloud-DevOps-Capstone
spec:
  selector:
    matchLabels:
      app: Cloud-DevOps-Capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: Cloud-DevOps-Capstone
    spec:
      containers:
      - name: Cloud-DevOps-Container
        image: yaraselim1994/cloud-devops-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
